version: '3.3'
services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./config/php.ini:/usr/local/etc/php.ini
  db:
    image: mariadb:10.5.6
    container_name: db
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=AnythingYouDLike
volumes:
  wordpress_db: {}
